export const projects = [
  {
    titleKey: "items.0.title",
    descKey: "items.0.description",
    roleKey: "items.0.role",
    stack: ["React Native", "Nest.js", "OpenAI", "AWS S3", "PostgreSQL"],
    gradient: "from-violet-500/20 to-indigo-500/20",
    metrics: "AI-powered voice consultations",
  },
  {
    titleKey: "items.1.title",
    descKey: "items.1.description",
    roleKey: "items.1.role",
    stack: ["React Native", "Nest.js", "Stripe", "React", "Firebase", "AI"],
    gradient: "from-emerald-500/20 to-teal-500/20",
    metrics: "70,000+ users",
  },
  {
    titleKey: "items.2.title",
    descKey: "items.2.description",
    roleKey: "items.2.role",
    stack: ["Next.js", "Docker", "Tailwind", "TypeScript", "AWS", "Prisma ORM"],
    gradient: "from-amber-500/20 to-yellow-500/20",
    metrics: "40% faster LCP, 17% cost reduction",
  },
  {
    titleKey: "items.3.title",
    descKey: "items.3.description",
    roleKey: "items.3.role",
    stack: [
      "Next.js",
      "Nest.js",
      "PostgreSQL",
      "Redis",
      "Stripe",
      "Cloudflare",
    ],
    gradient: "from-blue-500/20 to-cyan-500/20",
    metrics: "700+ paid subs in 6 hours",
  },
  {
    titleKey: "items.4.title",
    descKey: "items.4.description",
    roleKey: "items.4.role",
    stack: ["Puppeteer", "Express.js", "Nginx", "React", "Node.js", "VPS"],
    gradient: "from-rose-500/20 to-orange-500/20",
    metrics: "Server-side animation rendering",
  },
  {
    titleKey: "items.5.title",
    descKey: "items.5.description",
    roleKey: "items.5.role",
    stack: ["React", "Nest.js", "PostgreSQL", "TypeORM", "AWS"],
    gradient: "from-sky-500/20 to-blue-500/20",
    metrics: "Mentor intern engineers, lead code reviews",
  },
  {
    titleKey: "items.6.title",
    descKey: "items.6.description",
    roleKey: "items.6.role",
    stack: [
      "React",
      "Next.js",
      "TypeScript",
      "Stripe",
      "Tailwind",
      "Playwright",
    ],
    gradient: "from-purple-500/20 to-fuchsia-500/20",
    metrics: "Platform refactor & signup flow re-architecture",
  },
  {
    titleKey: "items.7.title",
    descKey: "items.7.description",
    roleKey: "items.7.role",
    stack: ["React", "Next.js", "TypeScript", "Tailwind", "Tanstack Query"],
    gradient: "from-pink-500/20 to-rose-500/20",
    metrics: "Short-term engagement, feature delivery under tight deadlines.",
  },
] as const;
