export const skillCategories = [
  {
    key: "ai" as const,
    skills: [
      "Streaming LLM integrations (OpenAI, Groq...)",
      "Voice AI (STT/TTS, ElevenLabs)",
      "RAG pipelines",
      "Prompt engineering & context design",
    ],
  },
  {
    key: "frontend" as const,
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "TanStack Query",
      "Zustand",
      "Three.js",
      "WebSockets",
      "SEO",
    ],
  },
  {
    key: "backend" as const,
    skills: [
      "Node.js",
      "Nest.js",
      "PostgreSQL",
      "Redis",
      "MongoDB",
      "Kafka",
      "GraphQL",
      "Microservices",
      "Stripe",
    ],
  },
  {
    key: "mobile" as const,
    skills: [
      "React Native",
      "Expo",
      "Deep Linking",
      "Push Notifications",
      "In-App Purchases",
      "Ionic",
    ],
  },
  {
    key: "platform" as const,
    skills: [
      "AWS (S3, Lambda, RDS)",
      "Docker",
      "GitHub Actions",
      "Cloudflare",
      "Nginx",
      "Sentry",
      "GA4",
      "Amplitude",
      "Playwright",
      "Jest",
      "Meta ADs",
    ],
  },
] as const;
