export const skillCategories = [
  {
    key: "frontend" as const,
    skills: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Zustand",
      "Redux",
      "MobX",
      "TanStack Query",
      "Radix UI",
      "MUI",
      "Three.js",
      "WebSockets",
      "SEO",
    ],
  },
  {
    key: "backend" as const,
    skills: [
      "Node.js",
      "Nest.js",
      "Express.js",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Kafka",
      "TypeORM",
      "Prisma",
      "GraphQL",
      "REST API",
      "Microservices",
      "OpenAI / LLM",
    ],
  },
  {
    key: "mobile" as const,
    skills: [
      "React Native",
      "Native Modules",
      "Deep Linking",
      "Push Notifications",
      "Expo",
      "App Store Deployment",
      "Play Store Deployment",
      "In-App Purchases",
      "Ionic",
    ],
  },
  {
    key: "tools" as const,
    skills: [
      "Git",
      "Figma",
      "Sentry",
      "Postman",
      "Swagger",
      "Cursor",
      "Firebase",
      "Playwright",
      "Intercom",
      "Jest",
      "Telegram Bots",
      "Whatsapp Bots",
      "Twilio",
      "Stripe",
    ],
  },
  {
    key: "devops" as const,
    skills: [
      "AWS (S3, Lambda, RDS)",
      "Docker",
      "GitHub Actions",
      "Nginx",
      "Cloudflare",
      "VPS",
      "PM2",
      "CI/CD",
    ],
  },
  {
    key: "analytics" as const,
    skills: [
      "Crashlytics",
      "Amplitude",
      "Meta ADs",
      "Google Ads",
      "GA4",
      "Instabug",
      "Mixpanel",
      "Hotjar",
      "Datadog",
    ],
  },
] as const;
